/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author muhammadghazialghifari
 */
public class MenampilkanGambarButtonFull extends javax.swing.JFrame {

    /**
     * Creates new form MenampilkanGambar
     */
    public MenampilkanGambarButtonFull() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        gambar1 = new javax.swing.JLabel();
        gambar2 = new javax.swing.JLabel();
        gambar3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanel.setBackground(new java.awt.Color(204, 153, 0));
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Pantai Batakan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jButton2.setText("Pantai Teluk Tamiang");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, -1));

        jButton3.setText("Danau Sari Embun");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 130, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 130, -1));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 590, 45));

        imagePanel.setBackground(new java.awt.Color(204, 204, 0));
        imagePanel.setLayout(new java.awt.CardLayout());

        gambar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG_2457.jpg"))); // NOI18N
        gambar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(gambar1, "0");

        gambar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG_5636.jpg"))); // NOI18N
        imagePanel.add(gambar2, "1");

        gambar3.setBackground(new java.awt.Color(255, 255, 255));
        gambar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/IMG_7778.jpg"))); // NOI18N
        imagePanel.add(gambar3, "2");

        getContentPane().add(imagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 590, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    
               MenampilkanGambarButtonFull fullFramae = new MenampilkanGambarButtonFull();
                
               GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
               device.setFullScreenWindow(fullFramae);
                
               fullFramae.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JLabel gambar1;
    private javax.swing.JLabel gambar2;
    private javax.swing.JLabel gambar3;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
